- name: check sa for prom-server
  shell: "oc get sa -n openshift-kube-apiserver | grep prom-server | wc -l"
  register: prom_server_sa

- name: create sa to access prom_server profiles
  block:
    - name: create sa
      shell: "oc -n openshift-kube-apiserver create sa prom-server"

    - name: add cluster-admin clusterrrole
      shell: "oc create clusterrolebinding prom-admin --clusterrole cluster-admin --serviceaccount=openshift-kube-apiserver:prom-server"
  when: prom_server_sa.stdout | int == 0

- name: get the bearer token
  shell: "oc -n openshift-kube-apiserver sa get-token prom-server"
  register: prom_bearer_token
